package com.hbue.homeworkapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hbue.homeworkapp.dao.User;
import com.hbue.homeworkapp.dao.Course;
import com.hbue.homeworkapp.dao.Msg;

import com.hbue.homeworkapp.dao.UserDao;
import com.hbue.homeworkapp.dao.CourseDao;
import com.hbue.homeworkapp.dao.MsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig courseDaoConfig;
    private final DaoConfig msgDaoConfig;

    private final UserDao userDao;
    private final CourseDao courseDao;
    private final MsgDao msgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        msgDaoConfig = daoConfigMap.get(MsgDao.class).clone();
        msgDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        courseDao = new CourseDao(courseDaoConfig, this);
        msgDao = new MsgDao(msgDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Course.class, courseDao);
        registerDao(Msg.class, msgDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        courseDaoConfig.getIdentityScope().clear();
        msgDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public MsgDao getMsgDao() {
        return msgDao;
    }

}
