package com.hbue.homeworkapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MSG.
 */
public class Msg {

    private Long id;
    private String msgTitle;
    private String msgSender;
    private String msgInfo;
    private String msgPath;
    private String msgData;

    public Msg() {
    }

    public Msg(Long id) {
        this.id = id;
    }

    public Msg(Long id, String msgTitle, String msgSender, String msgInfo, String msgPath, String msgData) {
        this.id = id;
        this.msgTitle = msgTitle;
        this.msgSender = msgSender;
        this.msgInfo = msgInfo;
        this.msgPath = msgPath;
        this.msgData = msgData;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMsgTitle() {
        return msgTitle;
    }

    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle;
    }

    public String getMsgSender() {
        return msgSender;
    }

    public void setMsgSender(String msgSender) {
        this.msgSender = msgSender;
    }

    public String getMsgInfo() {
        return msgInfo;
    }

    public void setMsgInfo(String msgInfo) {
        this.msgInfo = msgInfo;
    }

    public String getMsgPath() {
        return msgPath;
    }

    public void setMsgPath(String msgPath) {
        this.msgPath = msgPath;
    }

    public String getMsgData() {
        return msgData;
    }

    public void setMsgData(String msgData) {
        this.msgData = msgData;
    }

}
