package com.hbueschoolhelper.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COURSE.
 */
public class Course {

    private Long id;
    private String courseName;
    private String teacherName;
    private String classRoom;
    private Integer week;
    private Integer classLength;
    private Integer oddWeeks;
    private Integer startweek;
    private Integer lastweek;

    public Course() {
    }

    public Course(Long id) {
        this.id = id;
    }

    public Course(Long id, String courseName, String teacherName, String classRoom, Integer week, Integer classLength, Integer oddWeeks, Integer startweek, Integer lastweek) {
        this.id = id;
        this.courseName = courseName;
        this.teacherName = teacherName;
        this.classRoom = classRoom;
        this.week = week;
        this.classLength = classLength;
        this.oddWeeks = oddWeeks;
        this.startweek = startweek;
        this.lastweek = lastweek;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    public String getClassRoom() {
        return classRoom;
    }

    public void setClassRoom(String classRoom) {
        this.classRoom = classRoom;
    }

    public Integer getWeek() {
        return week;
    }

    public void setWeek(Integer week) {
        this.week = week;
    }

    public Integer getClassLength() {
        return classLength;
    }

    public void setClassLength(Integer classLength) {
        this.classLength = classLength;
    }

    public Integer getOddWeeks() {
        return oddWeeks;
    }

    public void setOddWeeks(Integer oddWeeks) {
        this.oddWeeks = oddWeeks;
    }

    public Integer getStartweek() {
        return startweek;
    }

    public void setStartweek(Integer startweek) {
        this.startweek = startweek;
    }

    public Integer getLastweek() {
        return lastweek;
    }

    public void setLastweek(Integer lastweek) {
        this.lastweek = lastweek;
    }

}
