package com.hbueschoolhelper.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hbueschoolhelper.dao.Course;
import com.hbueschoolhelper.dao.Shop;

import com.hbueschoolhelper.dao.CourseDao;
import com.hbueschoolhelper.dao.ShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseDaoConfig;
    private final DaoConfig shopDaoConfig;

    private final CourseDao courseDao;
    private final ShopDao shopDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        courseDao = new CourseDao(courseDaoConfig, this);
        shopDao = new ShopDao(shopDaoConfig, this);

        registerDao(Course.class, courseDao);
        registerDao(Shop.class, shopDao);
    }
    
    public void clear() {
        courseDaoConfig.getIdentityScope().clear();
        shopDaoConfig.getIdentityScope().clear();
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

}
