package com.hbueschoolhelper.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOP.
 */
public class Shop {

    private Long id;
    private String shopName;
    private String shopImgPath;
    private String shopPhone;

    public Shop() {
    }

    public Shop(Long id) {
        this.id = id;
    }

    public Shop(Long id, String shopName, String shopImgPath, String shopPhone) {
        this.id = id;
        this.shopName = shopName;
        this.shopImgPath = shopImgPath;
        this.shopPhone = shopPhone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    public String getShopImgPath() {
        return shopImgPath;
    }

    public void setShopImgPath(String shopImgPath) {
        this.shopImgPath = shopImgPath;
    }

    public String getShopPhone() {
        return shopPhone;
    }

    public void setShopPhone(String shopPhone) {
        this.shopPhone = shopPhone;
    }

}
